-- MySQL Script generated by MySQL Workbench
-- ter 20 abr 2021 19:51:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `#__tipo_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__tipo_empresa` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(255) NOT NULL,
    `cnae` VARCHAR(45) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_tipo_emp_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_tipo_emp_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__tipo_destaque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__tipo_destaque` (
     `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
     `nome` VARCHAR(250) NULL,
    `tipo` ENUM('PROD', 'EMPR') NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_tipo_destaque_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_tipo_destaque_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__empresa` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
     `uuid` VARCHAR(45) NOT NULL,
    `nome_fantasia` VARCHAR(250) NOT NULL,
    `razao_social` VARCHAR(250) NOT NULL,
    `cnpj` VARCHAR(14) NULL,
    `descricao` text NULL,
    `id_tipo_empresa` BIGINT (11) NULL,
    `id_tipo_destaque_ativo` BIGINT (11) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_empresa_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_empresa_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    INDEX `idx_empresa_nome` (`nome_fantasia` ASC) VISIBLE,
    INDEX `fk_empresa_tipo_empresa_idx` (`id_tipo_empresa` ASC) VISIBLE,
    UNIQUE INDEX `uuid_empresa` (`uuid` ASC) VISIBLE,
    INDEX `fk_empresa_tipo_destque_ativo_idx` (`id_tipo_destaque_ativo` ASC) VISIBLE,
    CONSTRAINT `fk_empresa_tipo_empresa`
    FOREIGN KEY (`id_tipo_empresa`)
    REFERENCES `#__tipo_empresa` (`id`)
    
    ,
    CONSTRAINT `fk_empresa_tipo_destque_ativo` FOREIGN KEY (`id_tipo_destaque_ativo`) REFERENCES `#__tipo_destaque`
(`id`)  
 ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__pais` (
    `sigla` VARCHAR(3) NOT NULL,
    `nome` VARCHAR(255) NOT NULL,
    `sigla_moeda` VARCHAR(5) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_pais_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_pais_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`sigla`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__uf` (
    `uf` VARCHAR(3) NOT NULL,
    `nome` VARCHAR(250) NOT NULL,
    `sigla_pais` VARCHAR(45) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_uf_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_uf_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`uf`),
    INDEX `uf_pais_idx` (`sigla_pais` ASC) VISIBLE,
    CONSTRAINT `fk_uf_pais`
    FOREIGN KEY (`sigla_pais`)
    REFERENCES `#__pais` (`sigla`)
    
    )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__cidade` (
                                           `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
                                           `nome` VARCHAR(255) NOT NULL,
    `uf` VARCHAR(3) NOT NULL,
    `ddd` VARCHAR(3) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_cidade_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_cidade_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    INDEX `cidade_uf_idx` (`uf` ASC) VISIBLE,
    CONSTRAINT `fk_cidade_uf`
    FOREIGN KEY (`uf`)
    REFERENCES `#__uf` (`uf`)
    
    )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__telefone_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__telefone_empresa` (
        `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
        `id_empresa` BIGINT (11) NOT NULL,
        `id_cidade` BIGINT (11) NOT NULL,
        `tipo` ENUM('CASA', 'CELU', 'RECA', 'COME', 'OUTR') NOT NULL,
    `ddd` VARCHAR(3) NULL,
    `telefone` VARCHAR(45) NOT NULL,
    `exibir` TINYINT(1) NULL DEFAULT 1,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_telefone_emp_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_telefone_emp_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    INDEX `telefone_emp_empresa_idx` (`id_empresa` ASC) VISIBLE,
    INDEX `telefone_emp_cidade_idx` (`id_cidade` ASC) VISIBLE,
    CONSTRAINT `fk_telefone_emp_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `#__empresa` (`id`)
    
    ,
    CONSTRAINT `fk_telefone_emp_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `#__cidade` (`id`)
    
    )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__email_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__email_empresa` (
     `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
     `id_empresa` BIGINT (11) NOT NULL,
     `email` VARCHAR(255) NOT NULL,
    `exibir` TINYINT(1) NULL DEFAULT 1,
    `contato` TINYINT(1) NULL DEFAULT 1,
    `validado` DATETIME NULL,

    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_email_emp_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_email_emp_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    INDEX `email_emp_empresa_idx` (`id_empresa` ASC) VISIBLE,
    CONSTRAINT `fk_email_emp_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `#__empresa` (`id`)
    
    )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__logradouros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__logradouros` (
                                                `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
                                                `nome` VARCHAR(255) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_logradouro_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_logradouro_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__endereco_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__endereco_empresa` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `id_empresa` BIGINT (11) NOT NULL,
    `id_cidade` BIGINT (11) NOT NULL,
    `id_logradouro` BIGINT (11) NULL,
    `endereco` VARCHAR(250) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_endereco_emp_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_endereco_emp_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    `numero` VARCHAR(20) NULL,
    `complemento` VARCHAR(250) NULL,
    `bairro` VARCHAR(250) NULL,
    `cep` VARCHAR(8) NOT NULL,
    `exibir` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    INDEX `fk_endereco_emp_empresa_idx` (`id_empresa` ASC) VISIBLE,
    INDEX `fk_endereco_emp_cidade_idx` (`id_cidade` ASC) VISIBLE,
    INDEX `fk_endereco_emp_logradouro_idx` (`id_logradouro` ASC) VISIBLE,
    CONSTRAINT `fk_endereco_emp_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `#__empresa` (`id`)
    
    ,
    CONSTRAINT `fk_endereco_emp_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `#__cidade` (`id`)
    
    ,
    CONSTRAINT `fk_endereco_emp_logradouro`
    FOREIGN KEY (`id_logradouro`)
    REFERENCES `#__logradouros` (`id`)
    
    )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__tipo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__tipo_produto` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(250) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_tipo_produto_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_tipo_produto_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__caracteristica` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(250) NOT NULL,
    `tem_valor` TINYINT(1) DEFAULT 0,
    `tipo_valor` ENUM('TEXT','NUMERIC','CHECKED','OPTION','DINHEIRO','M²','CENTIMETROS','METROS','ALTURA','DINHEIRO'),
    `limit_chars_valor` BIGINT (11) NULL,
    `pattern` VARCHAR(250) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_caract_prod_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_caract_prod_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `#__caracteristica_valores_possiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__caracteristica_valores_possiveis` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `valor` VARCHAR(250) NOT NULL,
    `id_caracteristica` BIGINT (11) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_caract_prod_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_caract_prod_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    CONSTRAINT fk_vlr_caracteristica FOREIGN KEY (`id_caracteristica`) REFERENCES `#__caracteristica`(`id`),
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `#__caracteristicas_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__caracteristicas_produtos` (
    `id_produto` BIGINT (11) NOT NULL,
    `id_caracteristica` BIGINT (11) NOT NULL,
    `id_valor_possivel` BIGINT (11) NULL,
    `valor` varchar(255) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,


    CONSTRAINT fk_caract_prod_carac FOREIGN KEY (`id_caracteristica`) REFERENCES `#__caracteristica`(`id`),
    CONSTRAINT fk_caract_prod_produto FOREIGN KEY (`id_produto`) REFERENCES `#__produto`(`id`),
    CONSTRAINT fk_caract_prod_valor FOREIGN KEY (`id_valor_possivel`) REFERENCES `#__caracteristica_valores_possiveis`(`id`),

    CONSTRAINT fk_caract_prod_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_caract_prod_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id_produto`,`id_caracteristica`))
    ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `#__tipo_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__tipo_medida` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(250) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_tipo_medida_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_tipo_medida_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__produto` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(45) NOT NULL,
    `nome` VARCHAR(250) NOT NULL,
    `descricao` text NULL,
    `id_empresa` BIGINT (11) NOT NULL,
    `id_tipo_produto` BIGINT (11) NOT NULL,
    `id_medida` BIGINT (11) NOT NULL,
    `quantidade_medida` DECIMAL(12,2) NULL,
    `altura` DECIMAL(10,5) NULL,
    `largura` DECIMAL(10,5) NULL,
    `profundidade` DECIMAL(10,5) NULL,
    `peso` DECIMAL(10,5) NULL,
    `id_tipo_destaque_ativo` BIGINT (11) NULL,
    `exibir` TINYINT(1) NULL,
    `exibir_fim` DATETIME NULL,
    `exibir_inicio` DATETIME NOT NULL DEFAULT NOW(),
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_produto_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_produto_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uuid_produto` (`uuid` ASC) VISIBLE,
    INDEX `fk_produto_empresa_idx` (`id_empresa` ASC) VISIBLE,
    INDEX `fk_produto_tipop_produto_idx` (`id_tipo_produto` ASC) VISIBLE,
    INDEX `fk_produto_medida_idx` (`id_medida` ASC) VISIBLE,
    INDEX `fk_produto_tipo_destaque_idx` (`id_tipo_destaque_ativo` ASC) VISIBLE,
    CONSTRAINT `fk_produto_empresa` FOREIGN KEY (`id_empresa`) REFERENCES `#__empresa` (`id`),
    CONSTRAINT `fk_produto_tipop_produto` FOREIGN KEY (`id_tipo_produto`) REFERENCES `#__tipo_produto` (`id`),
    CONSTRAINT `fk_produto_medida` FOREIGN KEY (`id_medida`) REFERENCES `#__tipo_medida` (`id`),
    CONSTRAINT `fk_produto_tipo_destaque` FOREIGN KEY (`id_tipo_destaque_ativo`) REFERENCES `#__tipo_destaque` (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__foto_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__foto_produto` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(45) NOT NULL,
    `nome_arquivo` VARCHAR(250) NOT NULL,
    `descricao` VARCHAR(250) NOT NULL,
    `mimetype` VARCHAR(45) NOT NULL,
    `extencao` VARCHAR(4) NOT NULL,
    `id_produto` BIGINT (11) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_foto_produto_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_foto_produto_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uuid_foto_produto` (`uuid` ASC) VISIBLE,
    INDEX `fk_foto_produto_produto_idx` (`id_produto` ASC) VISIBLE,
    CONSTRAINT `fk_foto_produto_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `#__produto` (`id`)
    
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__tabela_preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__tabela_preco` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(250) NOT NULL,
    `inicio` DATETIME NOT NULL,
    `fim` DATETIME NULL,
    `exibir` TINYINT(1) NULL DEFAULT 1,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_tabela_preco_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_tabela_preco_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__preco_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__preco_produto` (
    `id_produto` BIGINT (11) NOT NULL,
    `id_tabela_preco` BIGINT (11) NOT NULL,
    `preco` DECIMAL(10,2) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_preco_produto_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_preco_produto_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id_produto`, `id_tabela_preco`),
    INDEX `fk_preco_produto_tabela_preco_idx` (`id_tabela_preco` ASC) VISIBLE,
    CONSTRAINT `fk_preco_produto_produto` FOREIGN KEY (`id_produto`) REFERENCES `#__produto` (`id`) ,
    CONSTRAINT `fk_preco_produto_tabela_preco` FOREIGN KEY (`id_tabela_preco`) REFERENCES `#__tabela_preco` (`id`)
    
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__forma_pagamento` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(250) NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_forma_pagamento_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_forma_pagamento_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__historico_destaque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__historico_destaque` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(45) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_historico_des_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_historico_des_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    `id_tipo_destaque` BIGINT (11) NOT NULL,
    `id_empresa` BIGINT (11) NOT NULL,
    `id_forma_pagamento` BIGINT (11) NOT NULL,
    `id_produto` BIGINT (11) NULL,
    `valor_pago` DECIMAL(10,2) NOT NULL,
    `data_contratado` DATETIME NOT NULL,
    `data_inicio` DATETIME NOT NULL,
    `data_pago` DATETIME NOT NULL,
    `identificador` VARCHAR(250) NULL,
    `comprovante` VARCHAR(250) NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_historico_destaque_empresa_idx` (`id_empresa` ASC) VISIBLE,
    INDEX `fk_historico_destaque_tipo_destaque_idx` (`id_tipo_destaque` ASC) VISIBLE,
    INDEX `fk_historico_destaque_forma_pagamento_idx` (`id_forma_pagamento` ASC) VISIBLE,
    INDEX `fk_historico_destaque_produto_idx` (`id_produto` ASC) VISIBLE,
    CONSTRAINT `fk_historico_destaque_empresa` FOREIGN KEY (`id_empresa`) REFERENCES `#__empresa` (`id`) ,
    CONSTRAINT `fk_historico_destaque_tipo_destaque` FOREIGN KEY (`id_tipo_destaque`) REFERENCES `#__tipo_destaque`
(`id`) ,
    CONSTRAINT `fk_historico_destaque_forma_pagamento` FOREIGN KEY (`id_forma_pagamento`) REFERENCES
    `#__forma_pagamento` (`id`) ,
    CONSTRAINT `fk_historico_destaque_produto` FOREIGN KEY (`id_produto`) REFERENCES `#__tipo_produto` (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__pessoa` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(255) NOT NULL,
    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,

    `sobre_nome` VARCHAR(45) NOT NULL,
    `genero` ENUM('M', 'F') NULL,
    `data_nascimento` DATE NULL,
    `cpf` VARCHAR(14) NULL,
    `id_usuario` BIGINT (11) NOT NULL,
    `id_empresa` BIGINT (11) NOT NULL,
    PRIMARY KEY (`id`, `nome`, `sobre_nome`),
    UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
    INDEX `fk_pessoa_empresa_idx` (`id_empresa` ASC) VISIBLE,
    CONSTRAINT fk_pessoa_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_pessoa_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_pessoa_empresa` FOREIGN KEY (`id_empresa`) REFERENCES `#__empresa` (`id`)
    
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__telefone_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__telefone_pessoa` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `id_pessoa` BIGINT (11) NOT NULL,
    `id_cidade` BIGINT (11) NOT NULL,
    `ddd` VARCHAR(3) NULL,
    `telefone` VARCHAR(45) NOT NULL,
    `tipo` ENUM('CASA', 'CELU', 'RECA', 'COME', 'OUTR') NOT NULL,
    `exibir` TINYINT(1) NULL DEFAULT 1,
    `contato` TINYINT(1) NULL DEFAULT 1,
    `validado` DATETIME NULL,

    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    PRIMARY KEY (`id`),
    CONSTRAINT fk_telefone_pessoa_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_telefone_pessoa_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_telefone_pessoa_pessoa` FOREIGN KEY (`id_pessoa`) REFERENCES `#__pessoa` (`id`) ,
    CONSTRAINT `fk_telefone_pessoa_cidade` FOREIGN KEY (`id_cidade`) REFERENCES `#__cidade` (`id`)
    
 ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `#__email_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__email_pessoa` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `id_pessoa` BIGINT (11) NOT NULL,
    `email` VARCHAR(255) NOT NULL,

    `exibir` TINYINT(1) NULL DEFAULT 1,
    `contato` TINYINT(1) NULL DEFAULT 1,
    `validado` DATETIME NULL,

    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    CONSTRAINT fk_email_pessoa_user_cri FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT fk_email_pessoa_user_alt FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),

    PRIMARY KEY (`id`),
    INDEX `fk_email_emp_pessoa_idx` (`id_pessoa` ASC) VISIBLE,
    CONSTRAINT `fk_email_emp_pessoa` FOREIGN KEY (`id_pessoa`) REFERENCES `#__pessoa` (`id`)
    
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `#__contato` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `id_email_pessoa_destino` BIGINT (11) NULL,
    `id_email_empresa_destino` BIGINT (11)  NULL,

    `id_users_origem` INT NULL,


    `id_mensagem_anterior` BIGINT (11) NULL,



    `mensagem` Text NOT NULL,
    `titulo` VARCHAR(255) NOT NULL,
    `id_produto_origem` BIGINT (11) NULL,



    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,


    PRIMARY KEY (`id`),
    CONSTRAINT `fk_contato_user_origem` FOREIGN KEY (`id_users_origem`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_contato_user_cri` FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_contato_user_alt` FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_contato_produto` FOREIGN KEY (`id_produto_origem`) REFERENCES `#__produto` (`id`),

    CONSTRAINT `fk_contato_email_pessoa` FOREIGN KEY (`id_email_pessoa_destino`) REFERENCES `#__email_pessoa` (`id`),
    CONSTRAINT `fk_contato_email_empresa` FOREIGN KEY (`id_email_empresa_destino`) REFERENCES `#__email_empresa` (`id`)
) ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `#__carrinho` (
    `id` BIGINT (11) NOT NULL AUTO_INCREMENT,
    `id_users_origem` INT NULL,



    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_carrinho_user_origem` FOREIGN KEY (`id_users_origem`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_carrinho_user_cri` FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_carrinho_user_alt` FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `#__carrinho_produto` (
    `id_carrinho`  BIGINT (11)  NOT NULL,
    `id_produto`  BIGINT (11)  NOT NULL,
    `id_tabela`  BIGINT (11)  NULL,
    `valor`  DECIMAL(12,2)  NULL,
    `quantidade` INT  DEFAULT 1,

    `status`            enum('A','R','B') DEFAULT 'A',
    `id_user_criador`   INT NOT NULL,
    `id_user_alterador` INT,
    `data_criado`      DATETIME NOT NULL,
    `data_alterado`    DATETIME,
    PRIMARY KEY (`id_carrinho`,`id_produto` ),

    CONSTRAINT `fk_carrinho_prod_id_tabela` FOREIGN KEY (`id_tabela`) REFERENCES `#__tabela_preco`(`id`),
    CONSTRAINT `fk_carrinho_prod_produto` FOREIGN KEY (`id_produto`) REFERENCES `#__produto`(`id`),
    CONSTRAINT `fk_carrinho_prod_carrinho` FOREIGN KEY (`id_carrinho`) REFERENCES `#__carrinho`(`id`),
    CONSTRAINT `fk_carrinho_prod_user_cri` FOREIGN KEY (`id_user_criador`) REFERENCES `#__users`(`id`),
    CONSTRAINT `fk_carrinho_prod_user_alt` FOREIGN KEY (`id_user_alterador`) REFERENCES `#__users`(`id`)
) ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
