-- MySQL Script generated by MySQL Workbench
-- ter 20 abr 2021 19:51:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


DROP TABLE  `#__tipo_empresa` ;
DROP TABLE `#__tipo_destaque` ;
DROP TABLE `#__empresa` ;
DROP TABLE `#__foto_empresa` ;
DROP TABLE `#__pais` ;
DROP TABLE `#__uf` ;
DROP TABLE `#__cidade` ;
DROP TABLE `#__telefone_empresa` ;
DROP TABLE `#__email_empresa` ;
DROP TABLE `#__logradouros` ;
DROP TABLE `#__endereco_empresa` ;
DROP TABLE `#__tipo_produto` ;
DROP TABLE `#__caracteristica` ;
DROP TABLE `#__caracteristica_valores_possiveis` ;
DROP TABLE `#__caracteristicas_produtos` ;
DROP TABLE `#__tipo_medida` ;
DROP TABLE `#__produto` ;
DROP TABLE `#__foto_produto` ;
DROP TABLE `#__tabela_preco` ;
DROP TABLE `#__preco_produto` ;
DROP TABLE `#__forma_pagamento` ;
DROP TABLE `#__historico_destaque` ;
DROP TABLE `#__pessoa` ;
DROP TABLE `#__telefone_pessoa` ;
DROP TABLE `#__email_pessoa`;
DROP TABLE `#__contato` ;
DROP TABLE `#__carrinho` ;
DROP TABLE `#__carrinho_produto` ;
DROP TABLE `#__url_busca` ;
DROP TABLE `#__convites` ;
DROP TABLE `#__emailblacklist`;
DROP TABLE `#__telefoneblacklist`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
